config/routes.rb
Rails.application.routes.draw do  
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/about', to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get 'posts/new'
  get 'posts/index'

  
  resources :posts
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    validates :title, presence: true, length: {minimum:5, maximum:25}
    validates :content, presence: true, length: {minimum:25, maximum:500}
    validates :user_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    before_create { self.remember_token = Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64.to_s) }
    before_save { self.email = email.downcase }
    validates :username, presence: true, length: { minimum:3, maximum:30}, uniqueness: true
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }

    has_secure_password
    has_many :posts
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :check_login, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post  = Post.new(post_params)
    if @post.save
      flash[:success] = "The post was created"
      redirect_to posts_index_path
    else
      flash[:danger] = "The post was not created"
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  private 

  def post_params
    params.require(:post).permit(:title, :content, :user_id)
  end

  def check_login
    redirect_to root_path if !logged_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase) 
        if user && user.authenticate(params[:session][:password])
            log_in user
            remember user
            flash[:success] = 'User logged in'
            redirect_to user 
        else
            flash.now[:danger] = 'Invalid email/password'
            render 'new'
        end
    end

    def destroy 
        log_out if logged_in?
        flash[:success] = "Logged out successfuly"
        redirect_to root_url
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @posts = Post.all
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save      
      log_in @user
      flash[:success] = "User created"
      redirect_to @user
    else
      flash[:danger] = "User was not created"
      render 'new'
    end
  end

  def show 
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "User updated"
      redirect_to @user
    else
      flash[:danger] = "User was not updated"
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def full_title(page_title='')
        base_title = "Exclusive ClubHouse"
        if page_title.empty?
            base_title
        else
            page_title + " | " + base_title
        end
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
        current_user        
    end
    
    
    def current_user
        if (user_id = session[:user_id])
            @current_user ||= User.find_by(id: user_id)
        elsif (user_id = cookies.encrypted[:user_id])
            user = User.find_by(id: user_id)
        end
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        forget current_user
        @current_user = nil
    end


    def remember (user)
        user.update_attribute(:remember_token, Digest::SHA1.hexdigest(SecureRandom.urlsafe_base64.to_s))
        cookies.permanent.encrypted[:user_id] = user.id
        cookies.permanent[:remember_token] = user.remember_token
    end

    def forget(user)
        user.update_attribute(:remember_token, nil)
        cookies.delete(:user_id)
        cookies.delete(:remember_token)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<%= link_to 'Home', root_path%> |
<%= link_to 'Contact', contact_path%> |
<%= link_to 'Help', help_path %> |
<%= link_to 'About', about_path %>

app/views/layouts/_header.html.erb
<%= link_to 'Home', root_path %> |
<% if logged_in? %>    
    <%= link_to "Profile", current_user %>
    <%= link_to "Write a post", posts_new_path %>
    <%= link_to 'Logout', logout_path, method: :delete %>
<% else %>
    <%= link_to 'Login', login_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
            <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= render 'layouts/header'%>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/posts/index.html.erb
<% provide(:title, 'Post Index') %>
<h1>All posts</h1>
<% @posts.each do |post| %>    
        <h3><%= post.title %></h3></br>
        <% if logged_in? %>
         <span><%= post.user.username %></span> 
        <% end %>
        <p><%= post.content %></p></br>    
<% end %>

<%= link_to 'Home', root_path %>

app/views/posts/new.html.erb
<% provide(:title, 'New Post') %>
<h1>New Post</h1>
<%= form_for @post do |f| %>
            <% if @post.errors.any? %>
                <div id="error_explanation">
                <div class="alert alert-danger">
                    The form contains <%= pluralize(@post.errors.count, "error") %>.
                </div>
                <ul>
                    <% @post.errors.full_messages.each do |msg| %>
                        <li><%= msg %></li>
                    <% end %>
                </ul>
                </div>
            <% end %>
            <%= f.label :title, 'Choose a Title' %></br>
            <%= f.text_field :title, placeholder: "Your title here", class: 'form-control'  %></br>
            <%= f.label :content, 'Write your post' %></br>
            <%= f.text_area :content, size: "30x10" , placeholder: "Your post here", class: 'form-control'  %></br>
            <%= f.hidden_field :user_id, :value => current_user.id %>
            <%= f.submit "Create" %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>About</h1>
<p>This website is a place where everyone can express their feelings towards someone</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>This is who we are</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>Here you can find all the information and FAQ</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>Welcome to the Exclusive ClubHouse</h1>
<h2>
This is the home page for the
<a href="#">Exclusive ClubHouse</a>
Website.
</h2>
<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<% @posts.each do |post| %>    
        <h3><%= post.title %></h3></br>
        <% if logged_in? %>
         <span><%= post.user.username %></span> 
        <% end %>
        <p><%= post.content %></p></br>    
<% end %>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
        <div class="alert alert-danger">
            The form contains <%= pluralize(@user.errors.count, "error") %>.
        </div>
        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
            <%= render 'errors', object: @user %>
            <%= f.label :username, 'Choose a Username' %></br>
            <%= f.text_field :username, placeholder: "Your username here", class: 'form-control'  %></br>
            <%= f.label :email, 'Add your Email' %></br>
            <%= f.text_field :email, placeholder: "Your email here", class: 'form-control'  %></br>
            <%= f.label :password, 'Your Password' %></br>
            <%= f.password_field :password, placeholder: "Your password here", class: 'form-control'  %></br>
            <%= f.label :password_confirmation, 'Re-type your Password' %></br>
            <%= f.password_field :password_confirmation, placeholder: "Your password confirmation here", class: 'form-control'  %></br>
            <%= f.submit "Create" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit' %>
<h1>Edit <%= @user.username %></h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
    <%= link_to '<<Back to user profile', @user %> </br>
    <%= link_to 'Delete', user_path(@user), method: :delete, data: { confirm: "Are you sure?" } %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= render 'form' %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<h1><%= @user.username %></h1>

<%= link_to "Edit", edit_user_path(@user) %>
<%= link_to "Home", root_path%>